# Production docker-compose for Dokploy deployment
# This file is optimized for production use with external Docker images
services:
  # Database services
  postgres_main:
    image: postgres:15
    container_name: postgres_main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
      - ./database/backups:/backups
      - ./database/sql:/sql
      - ./demo_data:/csv
      - ./sql:/sql
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MAIN_DB_USER} -d ${MAIN_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  holding_db:
    image: postgres:15
    container_name: holding_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${HOLDING_DB_USER}
      POSTGRES_PASSWORD: ${HOLDING_DB_PASS}
      POSTGRES_DB: ${HOLDING_DB_NAME}
    volumes:
      - holding_db_data:/var/lib/postgresql/data
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${HOLDING_DB_USER} -d ${HOLDING_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dead-letter-queue:
    image: postgres:15
    container_name: dead_letter_queue
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DLQ_DB_USER}
      POSTGRES_PASSWORD: ${DLQ_DB_PASS}
      POSTGRES_DB: ${DLQ_DB_NAME}
    volumes:
      - dlq_data:/var/lib/postgresql/data
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DLQ_DB_USER} -d ${DLQ_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Monitoring services
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - db_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - db_net
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - db_net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.13.2
    container_name: postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://${MAIN_DB_USER}:${MAIN_DB_PASS}@${MAIN_DB_HOST}:5432/${MAIN_DB_NAME}?sslmode=disable"
    networks:
      - db_net
    depends_on:
      - postgres_main

  # Logging services
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./logging/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./logging/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - db_net
    depends_on:
      - loki

  grafana-logs:
    image: grafana/grafana:10.0.0
    container_name: grafana-logs
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_LOGS_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_logs_data:/var/lib/grafana
      - ./logging/grafana-logs/provisioning:/etc/grafana/provisioning
      - ./logging/grafana-logs/dashboards:/var/lib/grafana/dashboards
    networks:
      - db_net
    depends_on:
      - loki
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application services
  api-receiver:
    image: ${DOCKERHUB_USERNAME}/analytics-infra-api-receiver:latest
    container_name: api_receiver
    restart: unless-stopped
    environment:
      PORT: 8080
      API_KEY: ${API_KEY}
      DB_HOST: ${HOLDING_DB_HOST}
      DB_PORT: 5432
      DB_USER: ${HOLDING_DB_USER}
      DB_PASS: ${HOLDING_DB_PASS}
      DB_NAME: ${HOLDING_DB_NAME}
    networks:
      - db_net
    depends_on:
      - holding_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sync-job:
    image: ${DOCKERHUB_USERNAME}/analytics-infra-sync-job:latest
    container_name: sync_job
    restart: unless-stopped
    environment:
      DB_HOST: ${HOLDING_DB_HOST}
      DB_PORT: 5432
      DB_USER: ${HOLDING_DB_USER}
      DB_PASS: ${HOLDING_DB_PASS}
      DB_NAME: ${HOLDING_DB_NAME}
      MAIN_DB_HOST: ${MAIN_DB_HOST}
      MAIN_DB_PORT: 5432
      MAIN_DB_USER: ${MAIN_DB_USER}
      MAIN_DB_PASS: ${MAIN_DB_PASS}
      MAIN_DB_NAME: ${MAIN_DB_NAME}
    networks:
      - db_net
    depends_on:
      - holding_db
      - postgres_main
    command: ["python", "sync_job.py"]

  data-validator:
    image: ${DOCKERHUB_USERNAME}/analytics-infra-data-validator:latest
    container_name: data-validator
    restart: unless-stopped
    environment:
      DB_HOST: ${HOLDING_DB_HOST}
      DB_PORT: 5432
      DB_USER: ${HOLDING_DB_USER}
      DB_PASS: ${HOLDING_DB_PASS}
      DB_NAME: ${HOLDING_DB_NAME}
      DLQ_DB_HOST: ${DLQ_DB_HOST}
      DLQ_DB_PORT: 5432
      DLQ_DB_USER: ${DLQ_DB_USER}
      DLQ_DB_PASS: ${DLQ_DB_PASS}
      DLQ_DB_NAME: ${DLQ_DB_NAME}
      VALIDATION_INTERVAL: 30
    networks:
      - db_net
    depends_on:
      - holding_db
      - dead-letter-queue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  health-monitor:
    image: ${DOCKERHUB_USERNAME}/analytics-infra-health-monitor:latest
    container_name: health-monitor
    restart: unless-stopped
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - API_RECEIVER_URL=http://api_receiver:8080
      - METABASE_URL=http://metabase:3000
      - HOLDING_DB_USER=${HOLDING_DB_USER}
      - HOLDING_DB_PASS=${HOLDING_DB_PASS}
      - HOLDING_DB_NAME=${HOLDING_DB_NAME}
      - MAIN_DB_USER=${MAIN_DB_USER}
      - MAIN_DB_PASS=${MAIN_DB_PASS}
      - MAIN_DB_NAME=${MAIN_DB_NAME}
    networks:
      - db_net
    depends_on:
      - prometheus

  # Database initialization
  db-init:
    image: postgres:15
    container_name: db_init
    restart: "no"
    environment:
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
      METABASE_APP_DB_NAME: ${METABASE_APP_DB_NAME}
      MAIN_DB_USER: ${MAIN_DB_USER}
      MAIN_DB_PASS: ${MAIN_DB_PASS}
      MAIN_DB_HOST: ${MAIN_DB_HOST}
      MAIN_DB_PORT: 5432
    volumes:    
      - ./scripts/init-metabase-db.sh:/init-metabase-db.sh
    networks:
      - db_net
    depends_on:
      postgres_main:
        condition: service_healthy
    command: >
      bash -c "
        chmod +x /init-metabase-db.sh &&
        /init-metabase-db.sh
      "

  # Visualization services
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    environment:
      MB_JETTY_PORT: 3000
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_APP_DB_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${MAIN_DB_USER}
      MB_DB_PASS: ${MAIN_DB_PASS}
      MB_DB_HOST: ${MAIN_DB_HOST}
      # Initial admin (first-run) and usability
      MB_SITE_NAME: ${MB_SITE_NAME:-Analytics Demo}
      MB_ADMIN_EMAIL: ${METABASE_ADMIN_EMAIL:-}
      MB_LOAD_SAMPLE_CONTENT: ${MB_LOAD_SAMPLE_CONTENT:-false}
      MB_LOAD_ANALYTICS_CONTENT: ${MB_LOAD_ANALYTICS_CONTENT:-true}
      MB_PASSWORD_COMPLEXITY: ${MB_PASSWORD_COMPLEXITY:-normal}
      MB_PASSWORD_LENGTH: ${MB_PASSWORD_LENGTH:-8}
      # Security and web settings
      MB_JETTY_HOST: 0.0.0.0
      MB_JETTY_REQUEST_HEADER_SIZE: ${MB_JETTY_REQUEST_HEADER_SIZE:-16384}
      MB_EMOJI_IN_LOGS: ${MB_EMOJI_IN_LOGS:-true}
      # CSP Configuration to fix UI issues for Dokploy/Traefik deployment
      MB_CONTENT_SECURITY_POLICY_NONCE: ${MB_CONTENT_SECURITY_POLICY_NONCE:-true}
      MB_CSP_SCRIPT_SRC: "${MB_CSP_SCRIPT_SRC_PROD:-'self' 'unsafe-inline' 'unsafe-eval' https://yourdomain.com https://analytics.yourdomain.com https://maps.google.com https://accounts.google.com}"
      MB_CSP_STYLE_SRC: "${MB_CSP_STYLE_SRC_PROD:-'self' 'unsafe-inline' https://yourdomain.com https://analytics.yourdomain.com https://accounts.google.com https://fonts.googleapis.com}"
      MB_CSP_FONT_SRC: "${MB_CSP_FONT_SRC_PROD:-'self' 'unsafe-inline' data: https://yourdomain.com https://analytics.yourdomain.com https://fonts.gstatic.com}"
      MB_CSP_IMG_SRC: "${MB_CSP_IMG_SRC_PROD:-'self' data: https: https://yourdomain.com https://analytics.yourdomain.com}"
      MB_CSP_CONNECT_SRC: "${MB_CSP_CONNECT_SRC_PROD:-'self' https://yourdomain.com https://analytics.yourdomain.com}"
      # Site URL for proper domain handling
      MB_SITE_URL: ${MB_SITE_URL:-https://analytics.yourdomain.com}
      # Email (optional, for invites, alerts, password reset)
      MB_EMAIL_SMTP_HOST: ${MB_EMAIL_SMTP_HOST:-}
      MB_EMAIL_SMTP_PORT: ${MB_EMAIL_SMTP_PORT:-587}
      MB_EMAIL_SMTP_USERNAME: ${MB_EMAIL_SMTP_USERNAME:-}
      MB_EMAIL_SMTP_PASSWORD: ${MB_EMAIL_SMTP_PASSWORD:-}
      MB_EMAIL_SMTP_SECURITY: ${MB_EMAIL_SMTP_SECURITY:-starttls}
      MB_EMAIL_FROM_ADDRESS: ${MB_EMAIL_FROM_ADDRESS:-${METABASE_ADMIN_EMAIL}}
      # Other common opts
      MB_ANON_TRACKING_ENABLED: ${MB_ANON_TRACKING_ENABLED:-false}
      MB_SEND_NEW_SSO_USER_ADMIN_EMAIL: ${MB_SEND_NEW_SSO_USER_ADMIN_EMAIL:-false}
    volumes:
      - metabase_data:/metabase-data
    networks:
      - db_net
    depends_on:
      - postgres_main
      - db-init
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_main_data:
  holding_db_data:
  dlq_data:
  prometheus_data:
  grafana_data:
  grafana_logs_data:
  loki_data:
  metabase_data:

networks:
  db_net:
    driver: bridge
