services:
  postgres_main:
    image: postgres:15
    container_name: postgres_main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "127.0.0.1:5432:5432"  # Bind to localhost only
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MAIN_DB_USER} -d ${MAIN_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  db_net:
    driver: bridge
